site_name: After Install Debian
nav:
    - Home: index.md
    - Control Tools: 
       - Git:
          - GitConfig: gitconfig.md
          - Model: model.md
       - Pip-Tools: piptools.md
       - MkDocs: mkdocs.md
    - Apps Installation:
       - Virtualbox: virtualbox.md
       - Python: python.md
       - R: rlang.md
       - Chrome: chrome.md
       - VS Code: vscode.md
       - Docker: docker.md
    - About: about.md    
